title:  Үздік GitHub
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
header_pages:
  - author.md
  - pikirler.md
  - kurstar.md
  - jazbalar.md
  - audiokitaptar.md
  - _esepter\A+B.md

permalink: /:categories/:title

collections:
  courses:
    output: true
  audiobooks:
    output: true
  esepter:
    output: true
    
minima:
  # Minima skin selection.
    # classic	           Default, light color scheme.
    # dark	             Dark variant of the classic skin.
    # auto	             Adaptive skin based on the default classic and dark skins.
    # solarized-light	   Light variant of solarized color scheme.
    # solarized-dark	   Dark variant of solarized color scheme.
    # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic
  
  social_links:
    - { platform: rss,       user_url: "https://t.me/Uzdik_BILIM", title: "Telegram"  }  
    - { platform: youtube,        user_url: "https://www.youtube.com/Uzdik" }
    - { platform: instagram,      user_url: "https://www.instagram.com/uzdik.bilim" }
    - { platform: facebook,       user_url: "https://www.facebook.com/uzdik.bilim" }
